# Generated by Django 3.0.3 on 2020-04-02 12:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('path', models.CharField(default='', max_length=250)),
                ('port', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersistentVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('access_mode', models.CharField(choices=[('ReadWriteOnce ', 'ReadWriteOnce'), ('ReadOnlyMany ', 'ReadOnlyMany'), ('ReadWriteMany ', 'ReadWriteMany ')], max_length=200)),
                ('storage', models.CharField(default='', max_length=250)),
                ('volume_mode', models.CharField(choices=[('Filesystem ', 'Filesystem'), ('Blockdevice ', 'Blockdevice')], max_length=200)),
                ('storage_class', models.CharField(blank=True, default='', max_length=200)),
                ('mount_path', models.CharField(blank=True, default='', max_length=200)),
                ('sub_path', models.CharField(blank=True, default='', max_length=200)),
                ('selector', models.CharField(blank=True, default='', max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('label', models.CharField(default='', max_length=250)),
                ('value', models.CharField(default='', max_length=250)),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('container', 'Container'), ('service', 'Service'), ('deployment', 'Deployment'), ('cluster_service', 'Cluster Service IP'), ('other', 'Other')], max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('value', models.CharField(default='', max_length=250)),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
