# Generated by Django 3.0.3 on 2020-04-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentvolume',
            name='access_mode',
            field=models.CharField(choices=[('ReadWriteOnce', 'ReadWriteOnce'), ('ReadOnlyMany', 'ReadOnlyMany'), ('ReadWriteMany', 'ReadWriteMany ')], max_length=200),
        ),
        migrations.AlterField(
            model_name='persistentvolume',
            name='volume_mode',
            field=models.CharField(choices=[('Filesystem', 'Filesystem'), ('Blockdevice', 'Blockdevice')], max_length=200),
        ),
    ]
