# Generated by Django 3.0.3 on 2020-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200403_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='persistentvolume',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='secret',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='variable',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('container', 'Container'), ('service', 'Service'), ('ingress', 'Ingress'), ('deployment', 'Deployment'), ('cluster_service', 'Cluster Service IP'), ('other', 'Other')], max_length=200),
        ),
    ]
