# Generated by Django 3.0.3 on 2020-04-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '__first__'),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('uid', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('developpement', 'Developpement'), ('test', 'test'), ('production', 'Production'), ('other', 'Other')], max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('settings', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('persistent_volume', models.ManyToManyField(blank=True, default='', to='store.PersistentVolume')),
                ('project', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('variable', models.ManyToManyField(blank=True, default='', to='store.Variable')),
            ],
        ),
    ]
