# Generated by Django 3.0.3 on 2020-04-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environnement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environnement',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
