# Generated by Django 3.0.3 on 2020-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environnement', '0002_environnement_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='environnement',
            name='color',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='environnement',
            name='color_fade',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
