# Generated by Django 3.0.3 on 2020-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('cron', 'cron'), ('import', 'Import'), ('config', 'config'), ('dailymail', 'dailymail'), ('schedule', 'schedule')], max_length=100)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_current', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
