# Generated by Django 3.0.3 on 2020-04-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='persistent_volume',
            field=models.ManyToManyField(blank=True, default='', to='store.PersistentVolume'),
        ),
    ]
