# Generated by Django 3.0.3 on 2020-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_deployment_persistent_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='color',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='deployment',
            name='color_fade',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.CreateModel(
            name='ClusterIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('port', models.CharField(blank=True, default='', max_length=200)),
                ('color', models.CharField(blank=True, default='', max_length=250)),
                ('color_fade', models.CharField(blank=True, default='', max_length=250)),
                ('deployment', models.ManyToManyField(blank=True, default='', to='deployment.Deployment')),
            ],
        ),
    ]
