# Generated by Django 3.0.3 on 2020-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0003_auto_20200403_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterip',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='deployment',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
