# Generated by Django 3.0.3 on 2020-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environnement', '0004_environnement_slug'),
        ('deployment', '0004_auto_20200405_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterip',
            name='environnement',
            field=models.ManyToManyField(blank=True, default='', to='environnement.Environnement'),
        ),
    ]
