# Generated by Django 3.0.3 on 2020-04-02 12:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0001_initial'),
        ('environnement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('command', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('cron ', 'Cron'), ('job ', 'Job'), ('deamon ', 'Deamon ')], max_length=200)),
                ('schedule', models.CharField(blank=True, default='', max_length=200)),
                ('restart_policy', models.CharField(choices=[('OnFailure ', 'OnFailure'), ('Never ', 'Never'), ('always ', 'always ')], max_length=200)),
                ('back_off_limit', models.CharField(blank=True, default='5', max_length=200)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('container', models.ManyToManyField(blank=True, default='', to='container.Container')),
                ('environnement', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='environnement.Environnement')),
            ],
        ),
    ]
