# Generated by Django 3.0.3 on 2020-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_container_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='restart_policy',
            field=models.CharField(choices=[('OnFailure', 'OnFailure'), ('Never', 'Never'), ('always', 'always ')], max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('cron', 'Cron'), ('job', 'Job'), ('deamon', 'Deamon ')], max_length=200),
        ),
    ]
