# Generated by Django 3.0.3 on 2020-04-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('day', models.CharField(blank=True, default='', max_length=200)),
                ('day_time', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
