# Generated by Django 3.0.3 on 2020-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='ip',
            field=models.CharField(blank=True, default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='token',
            name='name_space',
            field=models.CharField(blank=True, default='default', max_length=200),
        ),
    ]
