# Generated by Django 3.0.3 on 2020-04-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('type', models.CharField(blank=True, choices=[('pixel', 'Lead'), ('click', 'click'), ('js', 'js')], default='visite', max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('uid', models.CharField(blank=True, default='', max_length=254)),
                ('ip', models.CharField(blank=True, default='', max_length=254)),
                ('element', models.CharField(blank=True, choices=[('view', 'view'), ('author', 'author')], default='', max_length=200)),
                ('id_element', models.CharField(blank=True, max_length=254)),
                ('day', models.CharField(blank=True, max_length=200)),
                ('day_time', models.CharField(blank=True, max_length=200)),
                ('type_conversion', models.CharField(blank=True, choices=[('form_lead', 'form_lead'), ('page_view', 'page_view'), ('click_btn', 'click_btn'), ('download_document', 'download_document'), ('play_video', 'play_video'), ('pourcent_video', 'play_video'), ('read_content', 'pourcent_video'), ('open_popup', 'open_popup'), ('other', 'other'), ('like', 'like'), ('bookmark', 'bookmark'), ('dislike', 'dislike')], default='', max_length=200)),
            ],
        ),
    ]
