# Generated by Django 3.0.3 on 2020-04-02 12:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environnement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('label', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('before_install', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('script', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('type', models.CharField(choices=[('travis', 'Travis CI'), ('gitlab', 'Gitlab')], max_length=200)),
                ('after_success', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('deploy', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('on_branch', models.CharField(default='', max_length=250)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('environnement', models.ManyToManyField(blank=True, default='', to='environnement.Environnement')),
            ],
        ),
    ]
