# Generated by Django 3.0.3 on 2020-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='label',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
