# Generated by Django 3.0.3 on 2020-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200403_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
