# Generated by Django 3.0.3 on 2020-04-02 12:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployment', '__first__'),
        ('store', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('code_base', 'Code Base'), ('software', 'Software'), ('plugin', 'Add-ons / Plugin'), ('cron', 'Cron Job'), ('other', 'Other')], max_length=200)),
                ('base_image', models.CharField(blank=True, default='', max_length=250)),
                ('image_name', models.CharField(blank=True, default='', max_length=250)),
                ('source', models.CharField(blank=True, default='', max_length=250)),
                ('port', models.CharField(blank=True, default='', max_length=250)),
                ('commands', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('cmd', models.CharField(default='', max_length=250)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deployment', models.ManyToManyField(blank=True, default='', to='deployment.Deployment')),
                ('persistent_volume', models.ManyToManyField(blank=True, default='', to='store.PersistentVolume')),
                ('variable', models.ManyToManyField(blank=True, default='', to='store.Variable')),
            ],
        ),
    ]
