# Generated by Django 3.0.3 on 2020-04-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='volume_path',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
