# Generated by Django 3.0.3 on 2020-04-02 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other')], max_length=200)),
                ('token', models.CharField(max_length=254)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('from_invitation', models.BooleanField(default=False)),
                ('token_invitation', models.CharField(blank=True, max_length=254)),
                ('about', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Invitation accepted', 'Invitation accepted'), ('Invitation pending', 'Invitation pending')], default='', max_length=200)),
                ('type', models.CharField(blank=True, choices=[('user', 'user'), ('author', 'author'), ('translator', 'translator'), ('collaborator', 'collaborator'), ('employe', 'employe'), ('supervisor', 'supervisor')], default='', max_length=200)),
                ('status_type', models.CharField(blank=True, choices=[('user', 'user'), ('freelance', 'freelance'), ('collaborator_interne', 'collaborator_interne'), ('collaborator_externe', 'collaborator_externe'), ('partner', 'partner')], default='', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/profil')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('internal-collaborator', 'Internal collaborator'), ('external-collaborator', 'External collaborator'), ('guest', 'Guest')], default='admin', max_length=200)),
                ('theme', models.CharField(choices=[('default', 'default'), ('dango', 'dango'), ('mint', 'mint'), ('forest', 'forest'), ('navy', 'navy'), ('imperial', 'imperial'), ('suryp', 'suryp'), ('fushia', 'fushia'), ('ultra', 'ultra'), ('gold', 'gold'), ('retro', 'retro'), ('pop', 'pop')], default='default', max_length=200)),
                ('layout_home', models.CharField(choices=[('default', 'default'), ('edge', 'edge'), ('scientist', 'The Scientist'), ('flow', 'flow'), ('astra', 'astra'), ('storm', 'storm'), ('chameleon', 'chameleon'), ('mechanic', 'mechanic'), ('mage', 'mage'), ('katana', 'katana'), ('vorpal', 'vorpal')], default='default', max_length=200)),
                ('tour_backend', models.BooleanField(default=False)),
                ('tour_site', models.BooleanField(default=False)),
                ('tour_editor', models.BooleanField(default=False)),
                ('newsletter_subscribe', models.BooleanField(default=False)),
                ('block_access', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
