# Generated by Django 3.0.3 on 2020-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('uid', models.CharField(max_length=200)),
                ('name_space', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('Google_cloud', 'Google Cloud'), ('aws', 'AWS'), ('heroku', 'Heroku'), ('digital_ocean', 'Digital Ocean')], max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
