# Generated by Django 3.0.3 on 2020-04-02 12:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environnement', '0001_initial'),
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('uid', models.CharField(blank=True, default='', max_length=200)),
                ('annotations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('domain', models.CharField(default='localhost', max_length=250)),
                ('accept_tls', models.BooleanField(default=False)),
                ('accept_ssl', models.BooleanField(default=False)),
                ('path', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('container', models.ManyToManyField(blank=True, default='', to='container.Container')),
                ('environnement', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='environnement.Environnement')),
            ],
        ),
    ]
