# Generated by Django 3.0.3 on 2020-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0002_ingress_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingress',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
